### ISSUE TITLE
Nice theme

### ISSUE THREAD

**Issue by DutchPete** [GustavoSZ124/Obsidian-Theme-Seamless-View#1]
I love the objective of the theme: to reduce the differences between live preview mode and read mode.

I am mostly in Live Preview mode but occasionally go to Reading mode, and was always annoyed that after changing from 1 to the other, the screen view of a note was never where it was before so you have to scroll up or down to get back to the right position — I don't use Canvas much.

I am surprised that the devs never picked this up — I don't know if a feature request or bug issue has been submitted for it. If not, I hope they will sherlock this aspect of your plug-in 🤣

**Comment by GustavoSZ124** [comment]
Thank you very much. I am also in live preview most of the time, but if I use the canvas a bit more, that’s where the difference in spacing between both modes becomes quite noticeable.

At some point, the devs added margins to the headers to try to space out the text, but the result was quite poor. Some people like having differences between the two modes, but I don't. Seeing that there was no theme with this approach, I decided to create my own, hehehe.

**Comment by DutchPete** [comment]
Yep, I agree with you. 👍
