### ISSUE TITLE
Numbered list offset when double digits

### ISSUE THREAD

**Issue by DutchPete** [GustavoSZ124/Obsidian-Theme-Seamless-View#2]
This is what I mean:

![image](https://github.com/user-attachments/assets/e38951ed-a1b9-4fec-a572-73bd5a2346e8)

Look at points 10,11, 12.
It does not happen with other themes, so Seamless needs to be amended.

**Comment by GustavoSZ124** [comment]
Oh I see, I'll fix it

**Comment by GustavoSZ124** [comment]
Done, I've already updated the theme to fix the error and even match the live preview lists with the read mode ones.

**Comment by DutchPete** [comment]
Excellent, thank you for the quick response!
